# Important Notes:
# Every field you add must be added to the expandProps map in
# buildSrc/src/main/groovy/multiloader-common.gradle if it is referenced from a resource file.

# Project
version=0.1.0+1.21.1
group=dev.riftal
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Creator Mods Suite
mod_author=Nasir Idrishi (Riftal Studios)
mod_id=creatormods
license=MIT
credits=Riftal Studios
description=Multi-loader skeleton for the Creator Mods Suite.
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.17+1.21.1
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=21.1.250
neoforge_loader_version_range=[4,)

# Libraries
geckolib_version=4.9.2
mixin_version=0.8.5
mixinextras_version=0.5.5
junit_version=5.14.4

# Gradle
org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=2G
org.gradle.daemon=true
org.gradle.caching=true
