package dev.riftal.creator.core;

import dev.riftal.creator.Constants;
import dev.riftal.creator.core.command.CoreCommands;
import dev.riftal.creator.core.config.CreatorConfig;
import dev.riftal.creator.features.arsenal.ArsenalFeature;
import dev.riftal.creator.features.colossus.ColossusFeature;
import dev.riftal.creator.features.events.EventsFeature;
import dev.riftal.creator.features.evolve.EvolveFeature;
import dev.riftal.creator.features.powers.PowersFeature;
import dev.riftal.creator.features.rules.RulesFeature;
import dev.riftal.creator.features.toolkit.ToolkitFeature;
import dev.riftal.creator.features.vault.VaultFeature;

import java.util.List;
import java.util.Optional;

/**
 * Loader-agnostic entry point. Holds the ordered list of every feature in the suite and drives
 * their lifecycle. The Fabric and NeoForge entry points do nothing but call into here.
 *
 * <p><b>Do not edit this file.</b> Every feature is already wired in; a feature agent only fills in
 * the body of its own {@code <Cap>Feature} class.
 */
public final class CreatorMods {

    /**
     * Every feature, in initialisation order. Order is stable and meaningful: {@code toolkit}
     * ships the recording primitives other features lean on, so it goes first.
     */
    public static final List<Feature> FEATURES = List.of(
            new ToolkitFeature(),
            new ColossusFeature(),
            new PowersFeature(),
            new RulesFeature(),
            new EvolveFeature(),
            new EventsFeature(),
            new ArsenalFeature(),
            new VaultFeature());

    private static List<Feature> active = List.of();
    private static boolean initialised;
    private static boolean clientInitialised;
    private static boolean serverInitialised;

    /**
     * Called once from each loader's main entry point, during mod construction. Loads the config,
     * then runs {@link Feature#registerContent()} and {@link Feature#initCommon()} for every
     * enabled feature.
     */
    public static void init() {
        if (initialised) {
            return;
        }
        initialised = true;

        CreatorConfig.load();
        active = FEATURES.stream().filter(f -> CreatorConfig.isEnabled(f.id())).toList();

        Constants.LOG.info("{} {} feature(s) enabled: {}",
                Constants.MOD_NAME,
                active.size(),
                active.stream().map(Feature::id).toList());
        List<String> disabled = FEATURES.stream()
                .map(Feature::id)
                .filter(id -> !CreatorConfig.isEnabled(id))
                .toList();
        if (!disabled.isEmpty()) {
            Constants.LOG.info("Disabled in {}: {}", CreatorConfig.fileName(), disabled);
        }

        CoreCommands.register();
        forEach("registerContent", Feature::registerContent);
        forEach("initCommon", Feature::initCommon);
    }

    /**
     * Called from each loader's client entry point. Never runs on a dedicated server.
     *
     * <p>Idempotent: NeoForge fires several client registration events whose relative order is not
     * guaranteed, and each of them calls this first so the feature's client content exists by the
     * time it is collected.
     */
    public static void initClient() {
        if (clientInitialised) {
            return;
        }
        clientInitialised = true;
        forEach("initClient", Feature::initClient);
    }

    /** Called from each loader's dedicated-server entry point. Idempotent. */
    public static void initServer() {
        if (serverInitialised) {
            return;
        }
        serverInitialised = true;
        forEach("initServer", Feature::initServer);
    }

    /** Features that survived the config filter, in order. Empty before {@link #init()}. */
    public static List<Feature> active() {
        return active;
    }

    /** Look a feature up by id, whether or not it is enabled. */
    public static Optional<Feature> byId(String id) {
        return FEATURES.stream().filter(f -> f.id().equals(id)).findFirst();
    }

    /** True if the feature is present and switched on in the config. */
    public static boolean isEnabled(String id) {
        return active.stream().anyMatch(f -> f.id().equals(id));
    }

    /**
     * Runs one lifecycle phase. A feature that throws is logged and skipped - one broken feature
     * must never take the whole suite (or the game) down with it.
     */
    private static void forEach(String phase, java.util.function.Consumer<Feature> phaseFn) {
        for (Feature feature : active) {
            try {
                phaseFn.accept(feature);
            } catch (Throwable t) {
                Constants.LOG.error("Feature '{}' threw during {}; it will be incomplete this run",
                        feature.id(), phase, t);
            }
        }
    }

    private CreatorMods() {
    }
}
