modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}"
issueTrackerURL = "https://github.com/riftal-studios/creator-mods/issues"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://github.com/riftal-studios/creator-mods"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}''' #mandatory (Supports multiline text)
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[mixins]]
config = "${mod_id}-toolkit.mixins.json"
[[mixins]]
config = "${mod_id}-colossus.mixins.json"
[[mixins]]
config = "${mod_id}-powers.mixins.json"
[[mixins]]
config = "${mod_id}-rules.mixins.json"
[[mixins]]
config = "${mod_id}-evolve.mixins.json"
[[mixins]]
config = "${mod_id}-events.mixins.json"
[[mixins]]
config = "${mod_id}-arsenal.mixins.json"
[[mixins]]
config = "${mod_id}-vault.mixins.json"
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "AFTER"
side = "BOTH"
